dist: xenial
language: python
python:
- '2.7'
- '3.5'
- '3.6'
- '3.7'
- 3.7-dev
- 3.8-dev
- nightly
- pypy3.5
install:
- pip install -r requirements-dev.txt
- pip install .
script:
- pylint tagged_union --py3k
- pytest --cov=tagged_union
after_success:
- coveralls
deploy:
  provider: pypi
  user: Carotti
  password:
    secure: L+UfoHD8ZxYzYLNDzrbuQJW0ct0sYA32oKwciQs8fKLc5kIoZ1T/iIkwMtHLwZ4wktTPmHVlfVXEAdtiNxfob1r6oD2GuU9X+jFk46Tt4O5nWkUrtK8R/bt0bNzV50rMaPNDtGz+D8F2cwM7OIbGmPIDGVTWnKLL+f2Z78L9p/J99BiOul3tIm2qyKDz8SFlkAZ5hm0ti0RBP5u++TqqDOUN7UQbsuFoqyxNSQDzGbL/eDD5ZHKiu/o6G9x+S5J7rfQAC7yGAbIgMfDZ4l4sk0ZXeQHALjcsTrvTqpxEjlqTO+CBFwU36RlQGOYAZqYf1X2yQ63Qj+Dt8tU0Qa4M/134q2dQh44cjLx8x7vFLDbEOz5LpN9AodPOB1GMSfKnMwm6NbYaR9p2eDBRWXH7qBROHeRu3Kxrj1BQJ3iWDrhYSRhdyAKsNAS0s+0vSPuRG5ybFzTx4gz9/oEMV7M/kKSNEGrP/Ged4uLBVX23iAslyplcpGfcq92CfL9IdLUlYOhk9CXrTE79ohR0VXxo4f3mjBnlWh1dtf0Rs89yzrKdhx/qGQg0gBDlschvy/0EUEz3UseUhFsNBLJOZjAVJGlGUR93/L41SX1rdq6NBqSVM1Q2yOsniOPUKjamFKyF9WZ3fPZeAbyi3Gp16HYLncxcBkIE1xMWOjw2b4xVlcY=
  on:
    tags: true
